# Validate any edits:  curl -X POST --data-binary @.codecov.yml https://codecov.io/validate
coverage:
  precision: 2          # show XX.XX %
  round: down           # 89.987 → 89.98 %
  status:               # ← GitHub “Checks”
    project:
      default:
        informational: true    # non‑blocking overall coverage  
        target: auto           # compare to base commit 
        threshold: 1%          # allow ±1 pp drift
    patch:
      default:
        informational: true    # non‑blocking diff coverage 
        target: 80%            # want 80 % on changed lines
        threshold: 1%

comment:
  layout: "diff, flags, files"   # keep Codecov’s 3‑panel comment
  behavior: default              # update a single comment per PR
  require_head: true             # ensure CI actually uploaded a report
  hide_project_coverage: false   # ← show project delta in the PR comment 
