version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"  # Adjust Python version if needed

sphinx:
  configuration: website/source/conf.py  # Adjust if your config is in a different location

python:
  install:
    - method: pip
      path: .
    - requirements: website/requirements.txt  # List dependencies for building docs
