name: ionerdss_env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pyqt=6
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - tqdm
  - jupyter
  - jupyterlab
  - ipykernel
  - scikit-learn
  - pyqtgraph
  - PyOpenGL
  - scipy
  - requests
  - ipympl
  - ipywidgets
  - pytest
  - pip
  - pip:
      - biopython