name: Run Unit Tests

on:
  push:
    branches:
      - main  # Change to your default branch if needed
    paths:
      - "ionerdss/**"      # Run tests only if files inside `mypackage/` change
      - "tests/**"          # Run tests only if files inside `tests/` change
      - ".github/workflows/unittest.yml"  # Run if workflow file is modified
  pull_request:
    branches:
      - main
    paths:
      - "ionerdss/**"      # Run tests only if files inside `mypackage/` change
      - "tests/**"          # Run tests only if files inside `tests/` change
      - ".github/workflows/unittest.yml"  # Run if workflow file is modified

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"  # Change to match your project

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install dependencies
          pip install pytest  # Ensure pytest is available

      - name: Run unit tests
        run: |
          export PYTHONPATH=$(pwd)
          pytest --junitxml=report.xml